CREATE DATABASE examen_pr
GO

USE examen_pr

CREATE TABLE TB_USER (
	ID INT NOT NULL IDENTITY,
    USUARIO VARCHAR(100) NOT NULL,
	CLAVE VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)
GO

CREATE TABLE TB_CARGO (
	ID INT NOT NULL IDENTITY,
    NOMBRE VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)
GO

CREATE TABLE TB_EMPLEADOS (
	ID INT NOT NULL IDENTITY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATETIME NOT NULL,
	AFP BIT NOT NULL,
	CARGO_ID INT NOT NULL,
	SUELDO DECIMAL(10, 2),
	PRIMARY KEY (ID),
	FOREIGN KEY (CARGO_ID) REFERENCES TB_CARGO(ID)
)
GO



